Accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
from .forms import LoginForm




app_name = 'accounts'
urlpatterns = [
    path('signup',views.signup_view, name= 'signup'),
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name= 'logout'),
    path('editprofile',views.edit_profile, name= 'editprofile'),
    
    path('<int:pk>/profile/',views.ProfilePageView.as_view(),name='profile'),
    
]

OTAKUTIME/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('' , views.home, name="home"),
    path('Video/', include('Video.urls')),
    path('Song/', include('Song.urls')),
    path('Wallpaper/', include('Wallpaper.urls')),
    path('Accounts/',include('Accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Song/urls.py
from django.urls import path
from . import views

app_name= "SONG_PAGE"
urlpatterns = [
    path('', views.song_page, name="song_page"),
    path('create',views.song_create, name="create"),
    path('<slug>',views.song_detail, name="detail"),
    path('',views.profile_song_page, name="profile_song_page"),

]

Video/urls.py
from django.urls import path
from . import views

app_name= "VIDEO_PAGE"
urlpatterns = [
    path('', views.video_page, name="video_page"),
    path('create',views.video_create, name="create"),
    path('<slug>',views.video_detail, name="detail"),
    path('',views.profile_video_page, name="profile_video_page"),

]

Accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django import forms



class CustomUser(AbstractUser):
    
    username         = models.CharField(max_length=100 , blank=True)
    email            = models.EmailField(_('email address'), unique=True)
    first_name       = models.CharField(max_length=30,blank=True)
    last_name        = models.CharField(max_length=50,blank=True)
    date_of_birth    = models.DateField(blank=True,null=True)

    profile_image    = models.ImageField(upload_to='profiles/image/',blank=True,default='image/Otaku.jpg' )
    background_image = models.ImageField(upload_to='profiles/image/',blank=True,default='image/Otaku.jpg' )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

Accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm , AuthenticationForm
from django.contrib.auth import get_user_model
from django.forms import PasswordInput, TextInput, EmailField

User=get_user_model()




class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(label='email',widget=forms.TextInput(attrs={'placeholder': 'email','class':'contactus'}))
    username = forms.CharField(label='username',widget=forms.TextInput(attrs={'placeholder': 'username','class':'contactus'}))
    password1 = forms.CharField(label='password1',widget=forms.PasswordInput(attrs={'placeholder': 'password','class':'contactus'}))
    password2 = forms.CharField(label='password2',widget=forms.PasswordInput(attrs={'placeholder': 'confirm password','class':'contactus'}))
    class Meta:
        model    = User
        fields = ('email','username','password1','password2')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        
        fields = ('email','username','first_name','last_name','date_of_birth','profile_image','background_image')



class LoginForm(forms.Form):
    
    email = forms.EmailField(label='email',widget=forms.EmailInput(attrs={'placeholder': 'Email Address','id':'id_email','class':'contactus',}))  
    password = forms.CharField(label='password',widget=forms.PasswordInput(attrs={'placeholder':'Password','id':'id_password','class':'contactus',}))

    class Meta:
        model = User
        fields = ('email','password')
        exclude = ['username']

  
   

Accounts/views.py
from django.shortcuts import redirect,render
from django.contrib.auth import login,logout
from django.contrib.auth.forms import AuthenticationForm
from . import models
from .forms import CustomUserCreationForm,CustomUserChangeForm

from django.contrib.auth import get_user_model
User=get_user_model()

from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.views import generic
from django.shortcuts import get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin


def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('home')

    else:
        form = CustomUserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()

            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        
        return redirect('home')

    return render(request,'../templates/Home.html')

@login_required(login_url="/accounts/login")
def edit_profile(request):
    
    if request.method == 'POST':
        form = CustomUserChangeForm(data=request.POST,instance=request.user ,files=request.FILES)
        if form.is_valid():
            
            form.save()
            return redirect('home')

    elif request.method == 'GET':
        print(request.user)
        form = CustomUserChangeForm(instance=request.user)

    context={'form':form}
    return render(request,'accounts/editprofile.html',context)


class ProfilePageView(LoginRequiredMixin,DetailView):
    model = User
    template_name = 'accounts/profile.html'

    def get_context_data(self,*args, **kwargs):
        
        context = super(ProfilePageView,self).get_context_data(*args, **kwargs)

        page_user =get_object_or_404(User,id=self.kwargs['pk'])

        
        context["page_user"] = page_user
        return context

Accounts/templates/Accounts/editprofile.html
{%extends 'base.html'%}
{%block content%}
<h1>Edit Profile</h1>
<form class="site-form" action="{% url 'accounts:editprofile' %}" method="post" enctype="multipart/form-data">
                            Email:{{form.email}}
                            Username:{{form.username}}
                            first name:{{form.first_name}}
                            last name:{{form.last_name}}
                            
                            profile image:{{form.profile_image}}
                            background image:{{form.background_image}}
                            date of birth:<input type="date" value="{{form.date_of_birth}}">
    {% csrf_token %}
    <input type="submit" value="Save">

</form>
{% endblock %}

Accounts/templates/Accounts/login.html
{%extends 'base.html'%}
{% load static %}
{% load widget_tweaks %}


{%block content%}


    <!-- Login -->
    <div id="contact" class="contact">
        <div class="container">

            <div class="row">

                <div class="col-md-12">

                    <form class="contact_bg" action="{% url 'accounts:login' %}" method="post">
                        <div class="row">
                            
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                {{form.username}}
                               
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                {{form.password}}
                               
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <button class="send">Login</button>
                            </div>
                            {% csrf_token %}
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
   
    <!-- end login -->
</html>

{% endblock %}

Accounts/templates/Accounts/profile.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
  <h1>My profile</h1>

  <img src="{{page_user.profile_image.url}}" alt="">


<img src="{{page_user.background_image.url}}" alt="" width=50% height=50%>

{{page_user.email}}
{{page_user.username}}
{{page_user.first_name}}
{{page_user.last_name}}

{% if page_user.date_of_birth %}

{{page_user.date_of_birth}}

{% else %}
<h1>date of birth not set yet</h1>

{% endif %}

<li>
  {% if user.is_authenticated %}
  <a href="{% url 'VIDEO_PAGE:create' %}">Upload new Video</a>
  <h1></h1>
  <a href="{% url 'VIDEO_PAGE:profile_video_page' %}">My Videos</a>
  <h1>
  </h1>
  <a href="{% url 'SONG_PAGE:create' %}">Upload new Song</a>
  <h1></h1>
  <a href="{% url 'SONG_PAGE:profile_song_page' %}">My Songs</a>
  {% endif %}


</li>
  <li>  
    {% for video in video %}
    <h2><a href="{% url 'VIDEO_PAGE:detail' slug=upload.slug %}">{{video.title}}</a></h2>
    <p>{{video.snippet}}</p>
    <p>{{video.date}}</p> 
    {% endfor %}  
  </li>
 
</div>
<a href="{% url 'home' %}">Return</a>
{% endblock %}

Accounts/templates/Accounts/signup.html
{%extends 'base.html'%}
{% load static %}
{% load widget_tweaks %}

{%block content%}


    <!-- signup -->
    <div id="contact" class="contact">
        <div class="container">

            <div class="row">

                <div class="col-md-12">

                    <form class="contact_bg" action="{% url 'accounts:signup' %}" method="post">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                {{form.email}}
                                
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                               
                                {{form.password1}}
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                
                                {{form.password2}}
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                
                                {{form.username}}
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <button class="send">Register</button>
                            </div>
                            {% csrf_token %}
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
   
    <!-- end signup -->
</html>

{% endblock %}