OTAKUTIME/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('' , views.home, name="home"),
    path('Video/', include('Video.urls')),
    path('Song/', include('Song.urls')),
    path('Wallpaper/', include('Wallpaper.urls')),
    path('Accounts/',include('Accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Song/urls.py
from django.urls import path
from . import views

app_name= "SONG_PAGE"
urlpatterns = [
    path('', views.song_page, name="song_page"),
    path('create',views.song_create, name="create"),
    path('<slug>',views.song_detail, name="detail"),
    path('',views.profile_song_page, name="profile_song_page"),

]

Video/urls.py
from django.urls import path
from . import views

app_name= "VIDEO_PAGE"
urlpatterns = [
    path('', views.video_page, name="video_page"),
    path('create',views.video_create, name="create"),
    path('<slug>',views.video_detail, name="detail"),
    path('',views.profile_video_page, name="profile_video_page"),

]

Video/models.py
from django.db import models
from django import forms
from Accounts.models import CustomUser
from autoslug import AutoSlugField


class Video(models.Model):
    title = models.CharField(max_length = 100)
    slug = AutoSlugField(populate_from='title')
    body = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add = True)
    video = models.FileField(upload_to='videos/')

    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[0:30] + ' ...'

Video/forms.py
from django import forms
from . import models

class Videocreate(forms.ModelForm):
    class Meta:
        model = models.Video
        fields = ['title','body','video']

Video/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.decorators import login_required
from . import models
from Video.forms import Videocreate


def video_page(request):
    videos = models.Video.objects.all().order_by('-date')
    args = {'videos':videos}
    return render(request, 'Video/video_list.html', args)

def profile_video_page(request):
    videos = models.Video.objects.all().order_by('-date')
    args = {'videos':videos}
    return render(request, 'Video/profile_video_list.html', args)


def video_detail(request, slug):

    video = models.Video.objects.get(slug=slug)
    return render(request, 'Video/video_detail.html',{'video':video})




@login_required(login_url = "/Accounts/login")
def video_create(request):
    if request.method == 'POST':
        form = Videocreate(request.POST,request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('VIDEO_PAGE:video_page')
    else:
        form = Videocreate()
        return render(request , 'Video/video_create.html',{'form':form})

Video/templates/Video/profile_video_page.html
{%extends 'base.html'%}
{%block title%}

{%endblock%}

{%block content%}
<div class="container">
  <h1>Post</h1>
  {% for video in video %}
  <h2><a href="{% url 'VIDEO_PAGE:detail' slug=video.slug %}">{{video.title}}</a></h2>
  
  <p>{{video.date}}</p> 
  {% endfor %}
</div>
<a href="{% url 'home' %}">Return</a>
{% endblock %}
  

Video/templates/Video/video_create.html
{%extends 'base.html'%}
{%block content%}

<div id="contact" class="contact">
    <div class="container">

        <div class="row">
                <h1>upload your song</h1>
            <div class="col-md-12">

                <form class="contact_bg" action="{% url 'VIDEO_PAGE:create' %}" method="post" enctype="multipart/form-data">
                    <div class="row">
                            


                        <div >
                        <label for="id_title"></label><input type="text" name="title" placeholder="Title" class="col-xl-6 col-lg-6 col-md-6 col-sm-12" required="" id="id_title">
                   <br> <label for="id_body"></label><input type="text" name="body" placeholder="About..." class="col-x1-6 col-lg-6 col-md-6 col-sm-12" required="" id="id_body"><br>
                   <br> <label for="id_video">Video:</label><input type="file" name="video" required="" id="id_video">
                                              
                        </div>
                            {% csrf_token %}
                         
                            <button class="send">Upload</button>
                        </div>
                        {% csrf_token %}
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

Video/templates/Video/video_detail.html
{%extends 'base.html'%}
{%block content%}


 <!-- about  -->
 <div id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>{{video.title}}</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="about-box">
                    <figure>
                        {% if video.video %}
                        <video width="1280" height="720" controls="controls">       
                         <source src="{{video.video.url}}#t=10" type="video/mp4"> 
                        </video>  
                        {% endif %}
                    </figure>

                    <p>{{video.body}}</p>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

Video/templates/Video/video_list.html
{%extends 'base.html'%}
{% load static %}

{%block content%}
<!-- our -->
<div id="games" class="our">
    <div class="container">   
    <div class="container-fluid">
       <div class="row">                    
         <div class="logo">
            <div class="col-md-8">
                <div class="titlepage">
                    <li class="button_login"> <a href="{% url 'VIDEO_PAGE:create' %}">Upload your Video</a> </li><br>
                </div>
              </div>
         </div> 
        </div>  
    </div> 
   
        
        <div class="col-lg-3 col-md-6 col-sm-6 ">
          <div class="address">
             <h1>Videos</h1>
          </div>
        </div>
  
  
        <div class="row">  

        {% if videos %}
          
        {% for video in videos %}
          <div class="col-md-12">
              <div class="row">

                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                      <div class="two-box">
                          <figure><video src="{{video.video.url}}#t=10" alt="#" width=100% height=100%></figure>
                      </div>
                  </div>

                  <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">

                      <div class="Games">
                          <h3>{{video.title}}</h3>
                          <p>{{video.snippet}}</p>
                          <a href="{% url 'VIDEO_PAGE:detail' slug=video.slug %}">Watch Now</a>
                      </div>
                  </div>
              </div>
          </div>
          <br><br>
          {% endfor %}

          {% else %}
          <h1>No Videos yet</h1>
          {% endif %}


      </div>
  </div>
</div>

<!-- end our -->

{% endblock %}
  

<!--div class="container">
  <h1>Videos</h1>
  <li>
    <li>
      {% if user.is_authenticated %}
      <a href="{% url 'VIDEO_PAGE:create' %}">Upload new Video</a>
    
      <a href="{% url 'VIDEO_PAGE:profile_video_page' %}">My Posts</a>
    
      {% endif %}
    
    
    </li>
  </li>
  {% for video in video %}
  <h2><a href="{% url 'VIDEO_PAGE:detail' slug=video.slug %}">{{video.title}}</a></h2>
  <video width="256" height="144" controls="controls">       
    <source src="{{video.video.url}}" type="video/mp4"> 
   </video>  
  <p>{{video.snippet}}</p>
  <p>{{video.date}}</p> 
  {% endfor %}
</div>
<a href="{% url 'home' %}">Return</a>-->