OTAKUTIME/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('' , views.home, name="home"),
    path('Video/', include('Video.urls')),
    path('Song/', include('Song.urls')),
    path('Wallpaper/', include('Wallpaper.urls')),
    path('Accounts/',include('Accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Song/urls.py
from django.urls import path
from . import views

app_name= "SONG_PAGE"
urlpatterns = [
    path('', views.song_page, name="song_page"),
    path('create',views.song_create, name="create"),
    path('<slug>',views.song_detail, name="detail"),
    path('',views.profile_song_page, name="profile_song_page"),

]

Song/models.py
from django.db import models
from django import forms
from Accounts.models import CustomUser
from autoslug import AutoSlugField

class Song(models.Model):
    title = models.CharField(max_length = 100)
    slug = AutoSlugField(populate_from='title')
    body = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add = True)
    song = models.FileField(upload_to='songs/songs/')
    image = models.ImageField(upload_to='songs/image/',blank=True)
    
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title
    
    def snippet(self):

        return self.body[0:30] + ' ...'
    

        

Song/forms.py
from django import forms
from . import models

class Songcreate(forms.ModelForm):
    
    class Meta:
        model = models.Song
        fields = ['title','body','song','image']

Song/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.decorators import login_required
from . import models
from Song.forms import Songcreate
from Accounts import views


def song_page(request):
    songs = models.Song.objects.all().order_by('-date')
    args = {'songs':songs}
    return render(request, 'Song/song_list.html', args)

def profile_song_page(request):
    songs = models.Song.objects.all().order_by('-date')
    args = {'songs':songs}
    return render(request, 'Song/profile_song_list.html', args)


def song_detail(request, slug):

    song = models.Song.objects.get(slug=slug)
    return render(request, 'Song/song_detail.html',{'song':song})


@login_required(login_url = "/Accounts/login")
def song_create(request):

    if request.method == 'POST':
        form = Songcreate(request.POST,request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('SONG_PAGE:song_page')
    else:
        form = Songcreate()
        return render(request , 'Song/song_create.html',{'form':form})

Song/templates/Song/profile_song_page.html
{%extends 'base.html'%}
{%block title%}

{%endblock%}

{%block content%}
<div class="container">
  <h1>Post</h1>
  {% for song in song %}
  <h2><a href="{% url 'SONG_PAGE:detail' slug=song.slug %}">{{song.title}}</a></h2>
  
  <p>{{song.date}}</p>
  
  {% endfor %}
</div>
<a href="{% url 'home' %}">Return</a>
{% endblock %}
  

Song/templates/Song/song_create.html
{%extends 'base.html'%}
{%block content%}

<div id="contact" class="contact">
    <div class="container">

        <div class="row">
                <h1>upload your song</h1>
            <div class="col-md-12">

                <form class="contact_bg" action="{% url 'SONG_PAGE:create' %}" method="post" enctype="multipart/form-data">
                    <div class="row">
                            


                        <div >
                        <label for="id_title"></label><input type="text" name="title" placeholder="Title" class="col-xl-6 col-lg-6 col-md-6 col-sm-12" required="" id="id_title">
                   <br> <label for="id_body"></label><input type="text" name="body" placeholder="About..." class="col-x1-6 col-lg-6 col-md-6 col-sm-12" required="" id="id_body"><br>
                   <br> <label for="id_song">Song:</label><input type="file" name="song" required="" id="id_song">
                        <label for="id_image">Image:</label><input type="file" name="image" accept="image/*" id="id_image">                      
                        </div>
                            {% csrf_token %}
                         
                            <button class="send">Upload</button>
                        </div>
                        {% csrf_token %}
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

Song/templates/Song/song_detail.html
{%extends 'base.html'%}
{%block content%}


 <!-- about  -->
 <div id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>{{song.title}}</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="about-box">
                    <figure>
                        <img src={{song.image.url}} alt="#" width=100% height=100%/>
                        {% if song.song %}
                            <audio controls>
                                <source src="{{song.song.url}}" type="audio/mp3">  
                            </audio>   
                        {% endif %}
                    </figure>

                    <p>{{song.body}}</p>
                    <p>{{song.date}}</p>
                   
                    
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

Song/templates/Song/song_list.html
{%extends 'base.html'%}
{% load static %}

{%block content%}
<!-- our -->
<div id="games" class="our">
  <div class="container">
      


    
      
          
    
      
  <div class="container-fluid">
     <div class="row">                    
       <div class="logo">
          <div class="col-md-8">
              <div class="titlepage">
                  <li class="button_login"> <a href="{% url 'SONG_PAGE:create' %}">Upload your Song</a> </li><br>
              </div>
            </div>
       </div> 
      </div>  
  </div> 
 




      <div class="col-lg-3 col-md-6 col-sm-6 ">
        <div class="address">
           <h1>Songs</h1>
        </div>
      </div>


      <div class="row">
        
        {% if songs %}
        {% for song in songs %}
          <div class="col-md-12 margin_bottom">
              <div class="row">

                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                      <div class="two-box">
                          <img src={{song.image.url}} alt="#" width=100% height=100%/>
                      </div>
                  </div>

                  <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">

                      <div class="Games">
                          <h3>{{song.title}}</h3><br>
                          <a href="{% url 'SONG_PAGE:detail' slug=song.slug %}">Go to Page</a>
                          <p>{{song.snippet}}</p>
                          <audio controls>
                            <source src="{{song.song.url}}" type="audio/mp3">
                            
                        </audio>
                      </div>
                  </div>
              </div>
          </div>
          {% endfor %}

          {% else %}
          <h1>No Songs yet</h1>
          {% endif %}

          

      </div>
  </div>
</div>

{% endblock %}