Accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
from .forms import LoginForm




app_name = 'accounts'
urlpatterns = [
    path('signup',views.signup_view, name= 'signup'),
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name= 'logout'),
    path('editprofile',views.edit_profile, name= 'editprofile'),
    
    path('<int:pk>/profile/',views.ProfilePageView.as_view(),name='profile'),
    
]

OTAKUTIME/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('' , views.home, name="home"),
    path('Video/', include('Video.urls')),
    path('Song/', include('Song.urls')),
    path('Wallpaper/', include('Wallpaper.urls')),
    path('Accounts/',include('Accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Song/urls.py
from django.urls import path
from . import views

app_name= "SONG_PAGE"
urlpatterns = [
    path('', views.song_page, name="song_page"),
    path('create',views.song_create, name="create"),
    path('<slug>',views.song_detail, name="detail"),
    path('',views.profile_song_page, name="profile_song_page"),

]

Video/urls.py
from django.urls import path
from . import views

app_name= "VIDEO_PAGE"
urlpatterns = [
    path('', views.video_page, name="video_page"),
    path('create',views.video_create, name="create"),
    path('<slug>',views.video_detail, name="detail"),
    path('',views.profile_video_page, name="profile_video_page"),

]

Wallpaper/urls.py
from django.urls import path
from . import views

app_name= "WALLPAPER_PAGE"
urlpatterns = [
    path('', views.wallpaper_page, name="wallpaper_page"),
    path('create',views.wallpaper_create, name="create"),
    path('<slug>',views.wallpaper_detail, name="detail"),
    path('',views.profile_wallpaper_page, name="profile_wallpaper_page"),

]

templates/Home.html
{%extends 'base.html'%}
{% load static %}

{%block content%}

    <!-- our -->
    <div id="games" class="our">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>Videos</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 margin_bottom">
                    <div class="row">

                        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                            <div class="two-box">
                                <figure><img src="{% static 'images/our-image1.jpg' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>

                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">

                            <div class="Games">
                                <h3>My hero Academia</h3>
                                <p>bal hajskdlasdkla sdl kasldk  kdslak dlasopd masoihd iasm dao sdko amsdo , odsa </p>
                                <a href="#">Free Download</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 margin_bottom">
                    <div class="row">

                        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                            <div class="two-box">
                                <figure><img src="{% static 'images/our-image2.jpg' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>

                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">

                            <div class="Games">
                                <h3>Sanke</h3>
                                <p>asdikj asod imasoi dmsi dmo maspod ,pasof,apso fnaps nfpas f </p>
                                <a href="#">Free Download</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="row">

                        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                            <div class="two-box">
                                <figure><img src="{% static 'images/our-image3.jpg' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>

                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">

                            <div class="Games">
                                <h3>random</h3>
                                <p>kasujhd aos mdoasi mdopa smdp ioampsd o dsoa pdoasn dopas d </p>
                                <a href="#">Free Download</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <!-- end our -->
    <!-- We are -->
    <div id="software" class="We_are">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>otaku

                        </h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                     <div class="box_bg">
                         <div class="box_bg_img">
                             <figure><img src="{% static 'images/soft.jpg' %}"width=100% height=100%></figure>
                         </div>
                     </div>
                 </div>
                 <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 border_right">
                     <div class="box_text">
                         <p> asldkm laskjfpsa mflkas foais mfomoimomomoiamsffpoa,spfo,asl.fpa;sopfaosnnfsinfoasi   iansfonasfian  i fanso nfoa insfo </p>
                         <a href="#">Read more</a>
                     </div>
                 </div> 
            </div>
        </div>
    </div>
    <!-- end We are -->

    <!-- about  -->
    <div id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>About Our Site</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="about-box">
                        <figure><img src="{% static 'images/about.jpg' %}" alt="#" /></figure>

                        <p> asdasijfopaisjf  ji jo ifjasoi fjaso ijfoi as
                            <br> asofno iun ub iubiasubfiuas  fausifbais basuif baisf bi</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- end abouts -->

    <!-- testimonial -->
    <div id="testimonial" class="testimonial">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>wallpapers</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <a href="{% url 'WALLPAPER_PAGE:wallpaper_page' %}"></a>
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 offset-md-2">
                    <div class="row box">
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                            <div class="testimonial_box">
                                <figure><img src="{% static 'images/test1.png' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                            <div class="testimonial_box">
                                <figure><img src="{% static 'images/test2.png' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                            <div class="testimonial_box">
                                <figure><img src="{% static 'images/test3.png' %}" alt="#" width=100% height=100%/></figure>
                            </div>
                        </div>
                    </div>
                    <div class="clients_box">
                        <h3>Jecoo</h3>
                        <p>asfsd fsd sd fsdfdh fgh th rt fdrt nd jn djyd
                            <br> djdfgjhdh df jdfgj dfghsf sh sh sgh 
                            <br>shs bnsb s s hjkgy hshbs</p>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- end testimonial -->

    <!-- contact -->
    <div id="contact" class="contact">
        <div class="container">

            <div class="row">

                <div class="col-md-12">

                    <form class="contact_bg">
                        <div class="row">
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <input class="contactus" placeholder="Name" type="text" name="Name">
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                <input class="contactus" placeholder="Phone" type="text" name="Email">
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                <input class="contactus" placeholder="Email" type="text" name="Email">
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <textarea class="textarea" placeholder="Message" type="text" name="Message"></textarea>
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <button class="send">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

</html>
{% endblock %}

templates/about.html
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>about</title>
  
    </head>
    <body>
        <h1>About</h1>
        <p>This website is for share and learn...</p>
    </body>
  </html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Otaku Time</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
<body class="main-layout">
    
        <!-- loader  -->
<div class="loader_bg">
    <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
</div>
<!-- end loader -->

    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="header-top">
            <div class="header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                            <div class="full">
                                <div class="center-desk">
                                    <div class="logo">
                                        <a href="index.html"><img src="../static/images/logo.png" alt="#" width=50% height=50%/></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                            
                                        <ul class="top_icon">
                                            {% if user.is_authenticated %}
                                            <form class="button_login"   action="{% url 'accounts:logout' %}" method="post" value="logout">
                                                {% csrf_token %}
                                                <button class="send">Logout</button>
                                            
                                            
                                        
                                                
                                        
                                            </form>   
                                            {% csrf_token %}
                                            {% else %}
                                            <li class="button_login"> <a href="{% url 'accounts:login' %}" method="post">login</a> </li>
                                            <li class="button_register"> <a href="{% url 'accounts:signup' %}" method="post">Register</a> </li>
                                            {% csrf_token %}
                                            {% endif %}
                                            <li class="mean-last">
                                             <a href="#"><img src="../static/images/search_icon.png" alt="#" /></a>
                                            </li>
                                        </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end header inner -->

            <!-- end header -->
            <section class="slider_section">
                <div class="banner_main">

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-2 padding_left0">
                                <div class="menu-area">
                                <div class="limit-box">
                                    <nav class="main-menu">
                                        <ul class="menu-area-main">
                                            <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                                            <li> <a href="{% url 'VIDEO_PAGE:video_page' %}">Videos</a> </li>
                                            <li> <a href="{%url 'WALLPAPER_PAGE:wallpaper_page'%}">Wallpapers</a> </li>                                
                                            <li> <a href="{%url 'SONG_PAGE:song_page'%}">Songs</a> </li>
                                            <li> <a href="#contact">Contact</a> </li>
                                           
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 ">
                            </div>
                             <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 ">
                                <div class="text-img">
                                   <figure><img src="{% static 'images/img.png' %}" alt="#" width=50% height=50%/></figure>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
        
           </section>
        </div>
    </header>
    {%block content%}

    {%endblock%}

    <!--  footer -->
    <footr>
        <div class="footer ">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2>Newsletter</h2>
                    </div>
                    <div class="col-md-10 offset-md-1">
                        <form class="news">
                            <input class="newslatter" placeholder="Enter Your Email" type="text" name="Enter Your Email">
                            <button class="submit">Subscribe</button>
                        </form>
                    </div>
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
                        <div class="row">
                            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 ">
                                <div class="address">
                                    <ul class="social_link">
                                        <li><a href="#"><img src="{% static 'icon/fb.png' %}"></a></li>
                                        <li><a href="#"><img src="{% static 'icon/tw.png' %}"></a></li>
                                        <li><a href="#"><img src="{% static 'icon/lin(2).png' %}"></a></li>
                                         <li><a href="#"><img src="{% static 'icon/instagram.png' %}"></a></li>
                                    </ul>
                                    <a href="index.html"> <img src="{% static 'images/logo.png' %}" alt="logo"></a>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6">
                                <div class="address">
                                    <h3>Quick links</h3>
                                    <ul class="Menu_footer">
                                        <li class="active"> <img src="{% static 'images/3.png' %}" alt="#"> <a href="#game">Game</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#software">Software</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#about">About</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#testimonial"> Testimonial</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#contact">Contact</a> </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6">
                                <div class="address">
                                    <h3>downloded</h3>
                                    <ul class="Links_footer">
                                        <li class="active"><img src="{% static 'images/3.png' %}" alt="#"> <a href="#">Lorem Ipsum </a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#">Simply random</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#">Roots in a</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#"> Piece</a> </li>
                                        <li><img src="{% static 'images/3.png' %}" alt="#"> <a href="#">Classical</a> </li>
                                    </ul>
                                </div>
                            </div>
    
                            <div class="col-lg-3 col-md-6 col-sm-6 ">
                                <div class="address">
                                    <h3>Contact us </h3>
                                    <ul class="loca">
                                        <li>
                                            <a href="#"><img src="{% static 'icon/loc.png' %}" alt="#" /></a>London 145
                                            <br>United Kingdom </li>
                                        <li>
                                            <a href="#"><img src="{% static 'icon/email.png' %}" alt="#" /></a>demo@gmail.com </li>
                                        <li>
                                            <a href="#"><img src="{% static 'icon/call.png' %}" alt="#" /></a>+12586954775 </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
    
                </div>
    
            </div>
            <div class="copyright">
                <div class="container">
                    <p>© 2019 All Rights Reserved. <a href="https://html.design/">Free html Templates</a></p>
                </div>
            </div>
        </div>
    </footr>
    <!-- end footer -->
</body>


<!--##################################   JAVASCRIPT   ##############################################-->




<!-- Javascript files-->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
<script src="{% static 'js/plugin.js' %}"></script>
<!-- sidebar -->
<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>

templates/test.html
@import url(https://fonts.googleapis.com/css?family=Roboto:400,300)
@import url(https://cdn.materialdesignicons.com/1.3.41/css/materialdesignicons.min.css)

$speed: 0.5

.wrap
  margin: 0 auto
  width: 500px
  color: white
  text-align: center
  text-shadow: 1px 1px 5px rgba(0,0,0,.3)

body, html 
  padding: 0
  margin: 0
  background: #455A64
  box-sizing: border-box
  font-family: 'Roboto', sans-serif
  padding-bottom: -50px
  color: black

  *, *:before, *:after
    box-sizing: inherit
    transition: all .5s ease
  
  a
    text-decoration: none
    color: white
    border-bottom: 1px dashed rgba(255,255,255,.5)
    &:hover
      text-shadow: 1px 1px 5px #000000
    
  .player
    margin-top: 50px
    width: 500px
    height: 75px
    background: white
    border-bottom: 4px #ccc solid
    position: relative
    color: black
    text-align: left
    text-shadow: none
    
    .album-art
      position: absolute
      left: 0
      width: 15%
      height: 100%
      box-shadow: 3px 0 3px 0 rgba(0,0,0,.4)
      padding: 5px
      .cover
        width: 100%
        height: 100%
        box-shadow: 0 0 3px 2px rgba(0,0,0,0.25)
        background: url('https://upload.wikimedia.org/wikipedia/en/6/67/Foo_Fighters_8LP_Sonic_Highways.jpg')
        background-size: cover
    .description
      position: relative
      width: 60%
      height: 50px
      top: 20%
      left: 20%
      overflow: hidden
      .title
        color: black
        font-size: 24px
        font-weight: 100
      .sub-title
        font-size: 13px
        font-weight: 100
        color: #999
      
    .play-button
      position: absolute
      width: 55px
      height: 55px
      right: 10%
      border-radius: 50%
      top: -25px
      background: white
      box-shadow: 0 3px 20px 0 rgba(0,0,0,0.35)
      text-align: center
      line-height: 57px
      font-size: 26px
      color: #D32F2F
      cursor: pointer
      .lp-background
        transition: all .35s ease
        background: url("http://i65.tinypic.com/v5wy3b.png")
        background-size: cover
        animation: spin 1s infinite linear
        width: 100%
        height: 100%
        z-index: 1
        position: absolute
      i
        z-index: 100
      .mdi-pause
        z-index: 100
        position: absolute
        right: 17.5px
        top: 17.4px
        color: white
        font-size: 20px
      &:hover
        box-shadow: 0 3px 20px 0 rgba(0,0,0,0.5)
      
    .time-indicator
      position: absolute
      right: 11%
      top: 60%
      font-size: 13px
      font-weight: 100
      i
        color: #D32F2F
    
    .progress-bar
      width: 100%
      top: 100%
      opacity: 0
      height: 0
      position: absolute
      cursor: pointer
      .runner
        height: 4px
        background: #F44336
      
    .visualizer
      position: absolute
      top: 25%
      left: 37.5%
      width: 0%
      height: 50%
      display: flex
      align-items: center
      overflow: hidden
      div
        width: 2px
        background: #F44336
        float: left
        height: 0%
        margin-right: 5px
        transition: all .1s ease
        
    &.paused
      border-bottom: none
      .visualizer
        opacity: 0
      .lp-background
        opacity: 0
      .play-button
        .mdi-pause
          opacity: 0
          
    &.playing
      .description
        opacity: 0
      .album-art
        width: 0px
        opacity: 0
      .visualizer
        left: 5%
        width: 65%
      .progress-bar
        height: 4px
        margin: 0
        opacity: 1
      .description
        left: 0%
        opacity: 0
      .play-button
        background: transparent
        .mdi-play
          opacity: 0
      
      
@keyframes spin
  0% 
    transform: rotate(0deg)
  100%
    transform: rotate(360deg)